### ISSUE TITLE
Most builder types are unexported, and thus not visible in rustdoc

### ISSUE THREAD

**Issue by Kimundi** [paritytech/parity-wasm#127]
For an example, see https://paritytech.github.io/parity-wasm/parity_wasm/builder/fn.export.html

**Comment by NikVolf** [comment]
agreed, will fix 

but auto-generated documentation for these will have little value anyway, because of chaining and other stuff

Meanwhile, if you need help, see tests in most of these files:
https://github.com/paritytech/parity-wasm/tree/master/src/builder

**Comment by Kimundi** [comment]
Would you be fine with PRs that just add "pub use" statements at suitable places to make APIs visible? It seemed to me that in its current from, the crate is pretty much a "everything should be public" library, but maybe I misunderstood some explicit privacy barriers that should be kept.

**Comment by NikVolf** [comment]
Sure thing!

**Comment by RReverser** [comment]
This issue seems to still remain (or has been re-introduced). @NikVolf can you re-open please?

Few examples:

![image](https://user-images.githubusercontent.com/557590/69544605-fa25bc00-0f87-11ea-871b-e0dd251f1efe.png)

![image](https://user-images.githubusercontent.com/557590/69544644-0e69b900-0f88-11ea-9937-ccd13bdf2195.png)

![image](https://user-images.githubusercontent.com/557590/69544697-2ccfb480-0f88-11ea-940d-5d3347bfcf3e.png)
