### ISSUE TITLE
Support name section parsing

### ISSUE THREAD

**Issue by NikVolf** [paritytech/parity-wasm#129]
https://webassembly.github.io/spec/core/appendix/custom.html#name-section

**Comment by emk** [comment]
@NikVolf I just started work on "Name Section" parsing this morning, sticking to your style as much as possible, and I'd be happy to submit a PR soon (it's a pretty simple API). Have you already started work on this? Or should I go ahead and finish up my implementation (it's not very hard)?

**Comment by NikVolf** [comment]
@emk nope, haven't started anything, so please finish, thanks 👍

**Comment by emk** [comment]
Great! Should be fun. :-)

I do have one question. There's an "index map" data structure that shows up in a number of places, mapping relatively dense numeric indices to other values:

```rust
/// The names of the functions in this module.
pub struct FunctionNameSection {
    names: NameMap,
}

/// The names of the local variables in this module's functions.
pub struct LocalNameSection {
    local_names: IndexMap<NameMap>,
}

/// A map from indices to names.
type NameMap = IndexMap<String>;

/// How do we want to represent this type?
type IndexMap<T> = Vec<(u32, T)>;
```

We could plausibly deserialize `IndexMap` in a number of different ways:

1. `Vec<(u32, T)>`: Closest to the raw file format, but slow to access and inconvenient to update. Also, we would need to make sure that the indices always got serialized in ascending order.
2. `Vec<Option<T>>`: Allocate a vector big enough to hold the largest function ID / local variable ID, and represent missing entries as `None`. Since the entries will usually tend to be fairly dense, this might make sense. Might need to implement some custom iterators, etc., to make it pleasant to use.
3. `BTreeMap<u32, T>`: Has lots of convenient APIs, and can easily be serialized in ascending order. Will probably require more memory than (2) in the common case, where the indices are dense. (After all, most hash tables need to allocate 2x the space and support probing.
4. `HashMap<u32, T>`: Like (3), but we'd have to manually sort it when serializing.

I'm thinking the natural choices here are (2) and (3). Probably (2) requires slightly more code, and would have a less familiar API than `BTreeMap`. But it would be more efficient, and we wouldn't necessarily want to commit to exposing a `BTreeMap`-based API anyways.

Any preferences? Thank you for your advice!

I think the most

**Comment by NikVolf** [comment]
I'd prefer `2.` since it is almost always the case that every function/global/local has the name, right?

it also allows us to avoid osrng-dependencies from hashmap/btreemap

**Comment by emk** [comment]
Sweet! 2 it is!
