### ISSUE TITLE
FuncBody structs do not have the function parameters in the vector of locals

### ISSUE THREAD

**Issue by Steampunkery** [paritytech/parity-wasm#247]
The parameters of a function should be put in the vector of local variables for the given function because the `get_local` instruction gets them like regular local variables. Any function which has local variables and parameters will not have them in the correct index of the locals vector because the index of a local variable should be offset by the parameters, which wasm counts as locals, as it should.

The solution is simple: add the parameters to the locals vector for each FuncBody. I would implement this change myself, but I'm not familiar with the code and I'm working on my final project. My final uses this library, which is how I stumbled upon this bug. For now I'll just implement a hack fix in my code, but a permanent fix would be nice.

**Comment by NikVolf** [comment]
Why so?

Parameters of the function and locals are not semantically equivalent, despite they share local index space. The number of parameters is governed by strong type reference, while locals are defined per function explicitly. Also, parity-wasm is not aware of the runtime behavior that put locals and arguments in the same local index space, parity-wasm is merely a format library and does not make assumptions about the validity of the program.

With this in mind, I think I will be against such change.

But how is this introduces difficulties for your project and how is it a bug? You need to be aware of the number of function arguments (which is always known, since functions signature are strongly-typed) to adjust the `get_local`/`set_local` operands, don't you? Can you show your example or actual code which has this problem?

**Comment by Steampunkery** [comment]
I might be missing something, but how can I get a `FunctionType` from it's `FuncBody`, assuming I'm iterating over the `bodies` from `code_section()`. Or is there a way to get both at once from the `name_section` or some other way?

**Comment by NikVolf** [comment]
From FuncBody, no way, but you can get `FunctionType` from the entry in [function section](https://paritytech.github.io/parity-wasm/parity_wasm/elements/struct.Module.html#method.function_section), use the index you have iterating the code_section, entries in `code_section` and `function_section` are 1-to-1

**Comment by Steampunkery** [comment]
Thanks, I figured they were 1-1 because that feels logical, but I've been burned before by assuming the logical thing.

**Comment by Steampunkery** [comment]
I don't see how I can get the `FunctionType` from the `Func` (which is a `u32`) that I get from the `function_section`. Is there a method that does that? I don't think `FunctionType`s are 1-1 with `Func`s because multiple functions can have the same type.

**Comment by pepyakin** [comment]
So it works like this:

1. the types section contains a vector of types. At the moment, there is only one type kind - `FunctionType`.
2. the function section contains a vector of type indicies.
3. each one of those points into the type section with a u32 index.

**Comment by NikVolf** [comment]
@Steampunkery try this: https://github.com/paritytech/parity-wasm/pull/253
