### ISSUE TITLE
Should `F64Const(u64)` be `F64Const(f64)`?

### ISSUE THREAD

**Issue by brian-carroll** [paritytech/parity-wasm#314]
Hi, I'm working on a compiler using parity_wasm and it's very helpful, thank you!

I was trying to generate floating-point constants and I noticed the enum members take unsigned integers as arguments. Is this a bug or intended behaviour?

```rust
    F32Const(u32),
    F64Const(u64),
```

https://github.com/paritytech/parity-wasm/blob/master/src/elements/ops.rs#L167-L168

It looks like a mistake but according to `git blame`, it was last modified 4 years ago so I'm surprised there are no other issues about it, open or closed.

If it's the intended behaviour, could you clarify how to use it? Should I be using `transmute` in an `unsafe` block? I looked in the docs, couldn't find any mention of it.

**Comment by athei** [comment]
@NikVolf should know.

**Comment by Robbepop** [comment]
The `u32` and `u64` are as intended since their semantics are simpler cross platform.

> Should I be using transmute in an unsafe block? I looked in the docs, couldn't find any mention of it.

Just use the following APIs:
- https://doc.rust-lang.org/1.54.0/std/primitive.f64.html#method.from_bits
- https://doc.rust-lang.org/1.54.0/std/primitive.f64.html#method.to_bits

And for `u32` and `f32` the respective mirrored APIs.

**Comment by brian-carroll** [comment]
Aha! Ok that explains it.
Great, I'll use those methods.
Thanks very much for your help.
