### ISSUE TITLE
Debugging of interpreted code

### ISSUE THREAD

**Issue by pchickey** [paritytech/parity-wasm#98]
I'm using the parity-wasm interpreter to run some code that isn't quite correct, so I sometimes encounter `Error::Memory` and other faults. At the moment, the only way I have to track down where these are caused is through the log macros, which isn't ideal.

I'd like to propose adding debugging information to the `Error` enum cases, where appropriate. I'm prototyping something that takes a subset of the `FunctionContext` struct (leaving out `function` and `externals`, to avoid having to add a lifetime annotation to `Error`) and adds it to `Error::Memory`, and then adding some functions that walk the `frame_stack` and show a backtrace, using the function export table to find human-readable names for frames when possible.

However, as I expect this would be a pretty invasive change to the library, I'd like to open it up to discussion of how to architect this change and what other concerns or use cases you have.

**Comment by pchickey** [comment]
It ended up being pretty ugly, but here is my first pass at threading a returnable context through the interpreter:

https://github.com/pchickey/parity-wasm/commit/214bf2a46ab2d6b03a444de116f9e5b03b0439d4

In order to avoid the borrows, and be able to get `PartialEq` and `Clone` traits for `Error`, I ended up having to create a bunch of new structs that were just like the old ones, leaving out the parts that make them efficiency or safe for concurrency. This isn't ideal, and at the moment they are perhaps poorly named and placed.

I also need to go and add `map_err` in many places throughout the `runner.rs` file, which is yet more boilerplate.

Either way, this was a good exercise because it showed me how tricky it is to do this well. Perhaps the team will have suggestions of how to improve this code, I know it is still a long way from perfect.

**Comment by NikVolf** [comment]
Ok, so after the discussion with the team, we think we need different approach to the debugging/tracing problem.

The idea is to have a optional tracing structure in the `ModuleInstance`. Once setup, it can also have different options for tracing levels (for example, it can track calls and/or memory access even when there were no errors) and be highly configurable/extendable overall 

If tracer structure is present (not `None`), the reference to this tracing interface should be passed in  along with `CallerContext`/`FunctionContext` in optional reference field and any invocation of commands (`run_*` functions) can check the availability of this tracer and invoke it's interface the way they prefer

One extra thing to consider is that invocation of tracer should be as simple as possible, because we might want to consider make a compilation option to exclude them from the build of `parity-wasm` completely

Does it make sense, Pat?

**Comment by pchickey** [comment]
Yes, this seems like a much better approach. I'm going to use my hacky code to track down my current bugs, if possible, but I'll look into implementing that approach soon.

**Comment by NikVolf** [comment]
Interpreter moved to `wasmi` crate

**Comment by pepyakin** [comment]
Related issue: https://github.com/paritytech/wasmi/issues/28
